import {
  Music,
  Clock,
  Heart,
  Library,
  ListMusic,
  User,
  Disc,
  Settings,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Volume2,
  VolumeX,
  Search,
  Plus,
  Minus,
  Share2,
  Edit,
  Folder,
  Tag,
  Trash2,
  ChevronRight,
  ChevronLeft,
  Menu,
  X,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  Sun,
  Moon,
  Laptop,
  Download,
  Upload,
  RefreshCw,
  Save,
  Loader2,
  Maximize2,
  Minimize2,
  Volume1,
  Volume,
  Repeat,
  Shuffle,
  MoreHorizontal,
  MoreVertical,
  Grid,
  List,
  Layout,
  Sliders,
  Mic,
  MicOff,
  Headphones,
  Radio,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Power,
  PowerOff,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Star,
  Bookmark,
  BookmarkMinus,
  History,
  Calendar,
  Bell,
  BellOff,
  MessageSquare,
  MessageCircle,
  Mail,
  Phone,
  Video,
  VideoOff,
  Camera,
  CameraOff,
  Image,
  ImageOff,
  File,
  FileText,
  FileAudio,
  FileVideo,
  FileImage,
} from "lucide-react"

export const Icons = {
  // Musik-bezogene Icons
  music: Music,
  clock: Clock,
  heart: Heart,
  library: Library,
  playlist: ListMusic,
  user: User,
  album: Disc,
  settings: Settings,
  play: Play,
  pause: Pause,
  next: SkipForward,
  previous: SkipBack,
  volume: Volume2,
  mute: VolumeX,
  search: Search,
  add: Plus,
  remove: Minus,
  share: Share2,
  edit: Edit,
  folder: Folder,
  tag: Tag,
  delete: Trash2,
  
  // Navigation und UI
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  menu: Menu,
  close: X,
  check: Check,
  alert: AlertCircle,
  info: Info,
  help: HelpCircle,
  sun: Sun,
  moon: Moon,
  system: Laptop,
  
  // Aktionen
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  save: Save,
  loading: Loader2,
  maximize: Maximize2,
  minimize: Minimize2,
  volumeLow: Volume1,
  volumeMedium: Volume,
  repeat: Repeat,
  shuffle: Shuffle,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  grid: Grid,
  list: List,
  layout: Layout,
  sliders: Sliders,
  
  // Hardware und Status
  mic: Mic,
  micOff: MicOff,
  headphones: Headphones,
  radio: Radio,
  wifi: Wifi,
  wifiOff: WifiOff,
  battery: Battery,
  batteryCharging: BatteryCharging,
  power: Power,
  powerOff: PowerOff,
  
  // Sicherheit und Sichtbarkeit
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  eyeOff: EyeOff,
  star: Star,
  bookmark: Bookmark,
  bookmarkOff: BookmarkMinus,
  
  // Zeit und Benachrichtigungen
  history: History,
  calendar: Calendar,
  bell: Bell,
  bellOff: BellOff,
  
  // Kommunikation
  message: MessageSquare,
  messageCircle: MessageCircle,
  mail: Mail,
  phone: Phone,
  
  // Medien
  video: Video,
  videoOff: VideoOff,
  camera: Camera,
  cameraOff: CameraOff,
  image: Image,
  imageOff: ImageOff,
  
  // Dateitypen
  file: File,
  fileText: FileText,
  fileAudio: FileAudio,
  fileVideo: FileVideo,
  fileImage: FileImage,
} 